{{- if .Values.detect.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "siem-plus.fullname" . }}-detect
  labels:
    {{- include "siem-plus.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "siem-plus.fullname" . }}-detect
  minReplicas: {{ .Values.detect.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.detect.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.detect.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
