apiVersion: v1
kind: Service
metadata:
  name: {{ include "siem-plus.fullname" . }}-ui
  labels:
    {{- include "siem-plus.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "siem-plus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
